# The port the application will run on
port = 7510
# Whether or not this instance is a development instance
development = false
# Which levels are allowed to be logged onto the console. In order of verbosity: "error", "warning", "info", "log", "debug"
log_level = ["error", "warning", "info", "log"]
# What all authorization headers should start with.
auth_header = "Basic"